name: Snapshot

on:
  push:
    branches:
      - develop

jobs:
  dist:
    if: github.repository == 'dita-ot/dita-ot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew
      - name: Snapshot distribution package deployment
        run: ./gradlew dist -Pcommit=${GITHUB_SHA} -PskipGenerateDocs=true --no-daemon
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-1'
          SOURCE_DIR: 'build/distributions'
      - name: Maven snapshot deployment
        run: |
          echo $GPG_PASSPHRASE > 24AC15F2.asc
          gpg --dearmor 24AC15F2.asc > 24AC15F2.gpg
          ./gradlew --no-daemon --info publish -PossrhUsername=$OSSRH_USERNAME -PossrhPassword=$OSSRH_PASSWORD -Psigning.password=$SIGNING_PASSWORD -Psigning.keyId=24AC15F2 -Psigning.secretKeyRingFile=.travis/24AC15F2.gpg
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
